version: "3.8"

services:
  vault:
    build:
      context: ./hashicorp-vault
    container_name: hashicorp-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-config:/vault/config
      - vault-file:/vault/file
      - vault-logs:/vault/logs

  vite-frontend:
    build:
      context: ./frontend
      args:
        VITE_VAULT_ADDR: http://localhost:8200
    container_name: vite-frontend
    ports:
      - "3000:80"
    depends_on:
      - vault
    environment:
      - VITE_VAULT_ADDR=http://localhost:8200

volumes:
  vault-config:
  vault-file:
  vault-logs:
